//
//  SelectVarietyRouter.swift
//  mowine
//
//  Created by Josh Freed on 7/4/17.
//  Copyright (c) 2017 BleepSmazz. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SelectVarietyRoutingLogic {
    func routeToSnapPhoto()
}

protocol SelectVarietyDataPassing {
    var dataStore: SelectVarietyDataStore? { get }
}

class SelectVarietyRouter: NSObject, SelectVarietyRoutingLogic, SelectVarietyDataPassing {
    weak var viewController: SelectVarietyViewController?
    var dataStore: SelectVarietyDataStore?

    // MARK: Routing

    func routeToSnapPhoto() {
        
    }
    
    //func routeToSomewhere(segue: UIStoryboardSegue?)
    //{
    //  if let segue = segue {
    //    let destinationVC = segue.destination as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //  } else {
    //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
    //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //    navigateToSomewhere(source: viewController!, destination: destinationVC)
    //  }
    //}

    // MARK: Navigation

    //func navigateToSomewhere(source: SelectVarietyViewController, destination: SomewhereViewController)
    //{
    //  source.show(destination, sender: nil)
    //}

    // MARK: Passing data

    //func passDataToSomewhere(source: SelectVarietyDataStore, destination: inout SomewhereDataStore)
    //{
    //  destination.name = source.name
    //}
}
