//
//  SnapPhotoViewController.swift
//  mowine
//
//  Created by Josh Freed on 7/8/17.
//  Copyright (c) 2017 BleepSmazz. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SnapPhotoDisplayLogic: class {
    func displayUsedImage(viewModel: SnapPhoto.UseImage.ViewModel)
}

class SnapPhotoViewController: UIViewController, SnapPhotoDisplayLogic {
    var interactor: SnapPhotoBusinessLogic?
    var router: (NSObjectProtocol & SnapPhotoRoutingLogic & SnapPhotoDataPassing)?

    
    
    // MARK: Object lifecycle

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }

    // MARK: Setup

    private func setup() {
        let viewController = self
        let interactor = SnapPhotoInteractor()
        let presenter = SnapPhotoPresenter()
        let router = SnapPhotoRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }

    // MARK: Routing

    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }

    // MARK: View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
    }

    // MARK: Pick an image

    @IBAction func takePhoto(_ sender: ButtonPrimary) {
        displayImagePickerController(.camera)
    }
    
    @IBAction func chooseFromLibrary(_ sender: ButtonPrimary) {
        displayImagePickerController(.photoLibrary)
    }
    
    func displayImagePickerController(_ sourceType: UIImagePickerController.SourceType) {
        let controller = UIImagePickerController()
        controller.sourceType = sourceType
        controller.delegate = self
        present(controller, animated: true, completion: nil)
    }
    
    // MARK: Use image
    
    func useImage(_ image: UIImage) {
        let request = SnapPhoto.UseImage.Request(image: image)
        interactor?.useImage(request: request)
    }
    
    func displayUsedImage(viewModel: SnapPhoto.UseImage.ViewModel) {
        performSegue(withIdentifier: "ConfirmPhoto", sender: nil)
    }
}

extension SnapPhotoViewController: UIImagePickerControllerDelegate, UINavigationControllerDelegate {
    func imagePickerController(_ picker: UIImagePickerController, didFinishPickingMediaWithInfo info: [UIImagePickerController.InfoKey : Any]) {
        picker.dismiss(animated: true) {
            if let image = info[.originalImage] as? UIImage {            
                self.useImage(image)
            }
        }
    }
    
    func imagePickerControllerDidCancel(_ picker: UIImagePickerController){
        picker.dismiss(animated: true, completion: nil)
    }
}
