//
//  SnapPhotoModels.swift
//  mowine
//
//  Created by Josh Freed on 7/8/17.
//  Copyright (c) 2017 BleepSmazz. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum SnapPhoto {
    // MARK: Use cases

    enum Something {

        struct Request {
        }

        struct Response {
        }

        struct ViewModel {
        }

    }

}
