//
//  SnapPhotoInteractor.swift
//  mowine
//
//  Created by Josh Freed on 7/8/17.
//  Copyright (c) 2017 BleepSmazz. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SnapPhotoBusinessLogic {
    func useImage(request: SnapPhoto.UseImage.Request)
}

protocol SnapPhotoDataStore {
    var wineType: WineType! { get set }
    var variety: WineVariety! { get set }
    var photo: UIImage? { get }
}

class SnapPhotoInteractor: SnapPhotoBusinessLogic, SnapPhotoDataStore {
    var presenter: SnapPhotoPresentationLogic?
    var wineType: WineType!
    var variety: WineVariety!
    var photo: UIImage?

    // MARK: Use image

    func useImage(request: SnapPhoto.UseImage.Request) {
        photo = request.image

        let response = SnapPhoto.UseImage.Response()
        presenter?.presentUsedImage(response: response)
    }
}
