//
//  SnapPhotoInteractor.swift
//  mowine
//
//  Created by Josh Freed on 7/8/17.
//  Copyright (c) 2017 BleepSmazz. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SnapPhotoBusinessLogic {
    func doSomething(request: SnapPhoto.Something.Request)
}

protocol SnapPhotoDataStore {
    var wineType: Type! { get set }
    var variety: Variety! { get set }
}

class SnapPhotoInteractor: SnapPhotoBusinessLogic, SnapPhotoDataStore {
    var presenter: SnapPhotoPresentationLogic?
    var worker: SnapPhotoWorker?
    var wineType: Type!
    var variety: Variety!

    // MARK: Do something

    func doSomething(request: SnapPhoto.Something.Request) {
        worker = SnapPhotoWorker()
        worker?.doSomeWork()

        let response = SnapPhoto.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
