//
//  SnapPhotoPresenter.swift
//  mowine
//
//  Created by Josh Freed on 7/8/17.
//  Copyright (c) 2017 BleepSmazz. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SnapPhotoPresentationLogic {
    func presentSomething(response: SnapPhoto.Something.Response)
}

class SnapPhotoPresenter: SnapPhotoPresentationLogic {
    weak var viewController: SnapPhotoDisplayLogic?

    // MARK: Do something

    func presentSomething(response: SnapPhoto.Something.Response) {
        let viewModel = SnapPhoto.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
