//
//  SnapPhotoRouter.swift
//  mowine
//
//  Created by Josh Freed on 7/8/17.
//  Copyright (c) 2017 BleepSmazz. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SnapPhotoRoutingLogic {
    func routeToConfirmPhoto(segue: UIStoryboardSegue)
    func routeToNameWine(segue: UIStoryboardSegue)
}

protocol SnapPhotoDataPassing {
    var dataStore: SnapPhotoDataStore? { get }
}

class SnapPhotoRouter: NSObject, SnapPhotoRoutingLogic, SnapPhotoDataPassing {
    weak var viewController: SnapPhotoViewController?
    var dataStore: SnapPhotoDataStore?

    // MARK: Routing

    func routeToConfirmPhoto(segue: UIStoryboardSegue)
    {
        let destinationVC = segue.destination as! ConfirmPhotoViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToConfirmPhoto(source: dataStore!, destination: &destinationDS)
    }
    
    func routeToNameWine(segue: UIStoryboardSegue)
    {
        let destinationVC = segue.destination as! NameWineViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToNameWine(source: dataStore!, destination: &destinationDS)
    }

    // MARK: Navigation

    //func navigateToSomewhere(source: SnapPhotoViewController, destination: SomewhereViewController)
    //{
    //  source.show(destination, sender: nil)
    //}

    // MARK: Passing data

    func passDataToConfirmPhoto(source: SnapPhotoDataStore, destination: inout ConfirmPhotoDataStore)
    {
        destination.wineType = source.wineType
        destination.variety = source.variety
        destination.photo = source.photo
    }
    
    func passDataToNameWine(source: SnapPhotoDataStore, destination: inout NameWineDataStore)
    {
        destination.wineType = source.wineType
        destination.variety = source.variety
        destination.photo = nil
    }
}
