//
//  MainMenuViewControllerTests.swift
//  mowine
//
//  Created by Josh Freed on 2/26/18.
//  Copyright (c) 2018 Josh Freed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import mowine
import XCTest
import Nimble

class MainMenuViewControllerTests: XCTestCase {
    // MARK: Subject under test

    var sut: MainMenuViewController!
    var window: UIWindow!
    let session = FakeSession()
    let router = MockMainMenuRouter()

    // MARK: Test lifecycle

    override func setUp() {
        super.setUp()
        window = UIWindow()
        setupMainMenuViewController()
        sut.session = session
        sut.router = router
    }

    override func tearDown() {
        window = nil
        super.tearDown()
    }

    // MARK: Test setup

    func setupMainMenuViewController() {
        let bundle = Bundle.main
        let storyboard = UIStoryboard(name: "Main", bundle: bundle)
        sut = storyboard.instantiateViewController(withIdentifier:"MainMenuViewController") as! MainMenuViewController
    }

    func loadView() {
        window.addSubview(sut.view)
        RunLoop.current.run(until: Date())
    }

    // MARK: Test doubles
    
    class MockMainMenuRouter: NSObject, MainMenuRoutingLogic {
        var routedToAddwine = false
        var routedToMyWines = false
        var routedToMyAccount = false
        var routedToFriends = false
        var routedToSignIn = false
        
        func routeToAddWine(segue: UIStoryboardSegue) {
            routedToAddwine = true
        }
        
        func routeToMyWines(segue: UIStoryboardSegue) {
            routedToMyWines = true
        }
        
        func routeToMyAccount(segue: UIStoryboardSegue) {
            routedToMyAccount = true
        }
        
        func routeToFriends(segue: UIStoryboardSegue) {
            routedToFriends = true
        }
        
        func routeToSignInScreen(segue: UIStoryboardSegue) {
            routedToSignIn = true
        }
    }

    // MARK: Tests

//    func test_myAccountButton_routesToMyAccount() {
//        // Given
//        session.loggedIn()
//        
//        // When
//        loadView()
//        sut.showMyAccount()
//        
//        // Then
//        expect(self.router.routedToSignIn).to(beFalse())
//        expect(self.router.routedToMyAccount).to(beTrue())
//    }
//    
//    func test_myAccountButton_routesToSignInWhenNotSignedIn() {
//        // Given
//        session.notLoggedIn()
//
//        // When
//        loadView()
//        sut.showMyAccount()
//
//        // Then
//        expect(self.router.routedToMyAccount).to(beFalse())
//        expect(self.router.routedToSignIn).to(beTrue())
//    }
}
