//
//  AddWineSummaryModels.swift
//  mowine
//
//  Created by Josh Freed on 9/21/17.
//  Copyright (c) 2017 BleepSmazz. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum AddWineSummary {
    // MARK: Use cases

    enum CreateWine {

        struct Request {
        }

        struct Response {
            var wine: Wine?
        }

        struct ViewModel {
            var photo: UIImage?
            var name: String
            var rating: Double
        }

    }

    enum UpdateRating {
        struct Request {
            var rating: Double
        }
        
        struct Response {
            
        }
        
        struct ViewModel {
            
        }
    }
    
    enum DeleteWine {
        struct Request {

        }
        
        struct Response {
            
        }
        
        struct ViewModel {
            
        }
    }
}
