//
//  AddWineSummaryRouter.swift
//  mowine
//
//  Created by Josh Freed on 9/21/17.
//  Copyright (c) 2017 BleepSmazz. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol AddWineSummaryRoutingLogic {
    func routeToMainMenu()
    func routeToEditWine()
}

protocol AddWineSummaryDataPassing {
    var dataStore: AddWineSummaryDataStore? { get }
}

class AddWineSummaryRouter: NSObject, AddWineSummaryRoutingLogic, AddWineSummaryDataPassing {
    weak var viewController: AddWineSummaryViewController?
    var dataStore: AddWineSummaryDataStore?

    // MARK: Routing
    
    func routeToMainMenu() {
        viewController?.navigationController?.popToRootViewController(animated: true)
    }
    
    func routeToEditWine() {
//        viewController?.navigationController?.popToRootViewController(animated: false)
        
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let destinationVC = storyboard.instantiateViewController(withIdentifier: "EditWineViewController") as! EditWineViewController
        destinationVC.output.wine = dataStore!.wine
        let nc = UINavigationController()
        nc.pushViewController(destinationVC, animated: false)
        viewController?.present(nc, animated: true, completion: nil)
    }
    
    //func routeToSomewhere(segue: UIStoryboardSegue?)
    //{
    //  if let segue = segue {
    //    let destinationVC = segue.destination as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //  } else {
    //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
    //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //    navigateToSomewhere(source: viewController!, destination: destinationVC)
    //  }
    //}

    // MARK: Navigation

    //func navigateToSomewhere(source: AddWineSummaryViewController, destination: SomewhereViewController)
    //{
    //  source.show(destination, sender: nil)
    //}

    // MARK: Passing data

    //func passDataToSomewhere(source: AddWineSummaryDataStore, destination: inout SomewhereDataStore)
    //{
    //  destination.name = source.name
    //}
}
