//
//  SortAndFilterModels.swift
//  mowine
//
//  Created by Josh Freed on 3/18/17.
//  Copyright (c) 2017 BleepSmazz. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct SortAndFilter {

    struct Something {

        struct Request {
        }

        struct Response {
        }

        struct ViewModel {
        }

    }

}
