//
//  SortAndFilterPresenter.swift
//  mowine
//
//  Created by Josh Freed on 3/18/17.
//  Copyright (c) 2017 BleepSmazz. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol SortAndFilterPresenterInput {
    func presentSomething(response: SortAndFilter.Something.Response)
}

protocol SortAndFilterPresenterOutput: class {
    func displaySomething(viewModel: SortAndFilter.Something.ViewModel)
}

class SortAndFilterPresenter: SortAndFilterPresenterInput {
    weak var output: SortAndFilterPresenterOutput!

    // MARK: - Presentation logic

    func presentSomething(response: SortAndFilter.Something.Response) {
        // NOTE: Format the response from the Interactor and pass the result back to the View Controller

        let viewModel = SortAndFilter.Something.ViewModel()
        output.displaySomething(viewModel: viewModel)
    }
}
