//
//  SortAndFilterViewController.swift
//  mowine
//
//  Created by Josh Freed on 3/18/17.
//  Copyright (c) 2017 BleepSmazz. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol SortAndFilterViewControllerInput {
    func displaySomething(viewModel: SortAndFilter.Something.ViewModel)
}

protocol SortAndFilterViewControllerOutput {
    func doSomething(request: SortAndFilter.Something.Request)
}

class SortAndFilterViewController: UITableViewController, SortAndFilterViewControllerInput {
    var output: SortAndFilterViewControllerOutput!
    var router: SortAndFilterRouter!

    // MARK: - Object lifecycle

    override func awakeFromNib() {
        super.awakeFromNib()
        SortAndFilterConfigurator.sharedInstance.configure(viewController: self)
    }

    // MARK: - View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
        doSomethingOnLoad()
    }

    // MARK: - Event handling

    func doSomethingOnLoad() {
        // NOTE: Ask the Interactor to do some work

        let request = SortAndFilter.Something.Request()
        output.doSomething(request: request)
    }

    // MARK: - Display logic

    func displaySomething(viewModel: SortAndFilter.Something.ViewModel) {
        // NOTE: Display the result from the Presenter

        // nameTextField.text = viewModel.name
    }
}
