//
//  MyAccountInteractor.swift
//  mowine
//
//  Created by Josh Freed on 2/27/18.
//  Copyright (c) 2018 Josh Freed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MyAccountBusinessLogic {
    func getUser(request: MyAccount.GetUser.Request)
    func signOut()
}

class MyAccountInteractor: MyAccountBusinessLogic {
    var presenter: MyAccountPresentationLogic?
    var worker: MyAccountWorker?

    // MARK: Get User

    func getUser(request: MyAccount.GetUser.Request) {
        worker?.fetchUserAccount(completion: { error in
            if error != nil {
                self.presenter?.presentErrorGettingUser()
            }
        }, userCallback: { user in
            let response = MyAccount.GetUser.Response(user: user)
            self.presenter?.presentUser(response: response)
        }, profilePictureCallback: { data in
            DispatchQueue.main.async {
                self.presenter?.presentProfilePicture(data: data)
            }
        })
    }
    
    // MARK: Sign Out
    
    func signOut() {
        worker?.signOut()
    }
}
