//
//  MyAccountViewController.swift
//  mowine
//
//  Created by Josh Freed on 2/27/18.
//  Copyright (c) 2018 Josh Freed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MyAccountDisplayLogic: class {
    func displayUser(viewModel: MyAccount.GetUser.ViewModel)
    func displayErrorGettingUser()
    func displayProfilePicture(image: UIImage?)
}

protocol MyAccountViewControllerDelegate: class {
    func didSignOut()
}

class MyAccountViewController: UIViewController, MyAccountDisplayLogic {
    var interactor: MyAccountBusinessLogic?
    weak var delegate: MyAccountViewControllerDelegate?

    override var preferredStatusBarStyle: UIStatusBarStyle {
        return .default
    }
    
    // MARK: Object lifecycle

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }

    // MARK: Setup

    private func setup() {
        let viewController = self
        let interactor = MyAccountInteractor()
        let presenter = MyAccountPresenter()
        viewController.interactor = interactor
        interactor.presenter = presenter
        interactor.worker = MyAccountWorker(
            session: JFContainer.shared.session,
            userRepository: JFContainer.shared.userRepository,
            profilePictureWorker: try! JFContainer.shared.container.resolve()
        )
        presenter.viewController = viewController
    }

    // MARK: View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
        
        profilePictureImageView.image = #imageLiteral(resourceName: "No Profile Picture")
        profilePictureImageView.clipsToBounds = true
        profilePictureImageView.contentMode = .scaleAspectFill

        getUser()
    }

    override func viewWillLayoutSubviews() {
        super.viewWillLayoutSubviews()
        profilePictureImageView.layer.cornerRadius = profilePictureImageView.frame.size.width / 2
    }

    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
    }
    
    @IBAction func unwindToMyAccount(_ unwindSegue: UIStoryboardSegue) {
    }
    
    // MARK: Get User

    @IBOutlet weak var profilePictureImageView: UIImageView!
    @IBOutlet weak var fullNameLabel: UILabel!
    @IBOutlet weak var emailAddressLabel: UILabel!

    func getUser() {
        let request = MyAccount.GetUser.Request()
        interactor?.getUser(request: request)
    }

    func displayUser(viewModel: MyAccount.GetUser.ViewModel) {
        fullNameLabel.text = viewModel.fullName
        emailAddressLabel.text = viewModel.emailAddress
    }
    
    func displayErrorGettingUser() {
        
    }
    
    // MARK: Sign Out
    
    @IBAction func tappedSignOut(_ sender: UIButton) {
        let alertController = UIAlertController(title: nil, message: nil, preferredStyle: .actionSheet)
        alertController.addAction(UIAlertAction(title: "Sign Out", style: .destructive, handler: { _ in
            self.signOut()
        }))
        alertController.addAction(UIAlertAction(title: "Cancel", style: .cancel, handler: nil))
        present(alertController, animated: true, completion: nil)
    }
    
    func signOut() {
        interactor?.signOut()
        delegate?.didSignOut()
    }
    
    // MARK: Display profile picture

    func displayProfilePicture(image: UIImage?) {
        profilePictureImageView.image = image
    }
}
