//
//  MyAccountPresenter.swift
//  mowine
//
//  Created by Josh Freed on 2/27/18.
//  Copyright (c) 2018 Josh Freed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MyAccountPresentationLogic {
    func presentUser(response: MyAccount.GetUser.Response)
    func presentErrorGettingUser()
}

class MyAccountPresenter: MyAccountPresentationLogic {
    weak var viewController: MyAccountDisplayLogic?

    // MARK: Get User

    func presentUser(response: MyAccount.GetUser.Response) {
        let viewModel = MyAccount.GetUser.ViewModel(
            fullName: response.user.fullName,
            emailAddress: response.user.emailAddress,
            profilePicture: response.user.profilePicture ?? #imageLiteral(resourceName: "No Profile Picture")
        )
        viewController?.displayUser(viewModel: viewModel)
    }
    
    func presentErrorGettingUser() {
        viewController?.displayErrorGettingUser()
    }
}
