//
//  WineDetailsPresenter.swift
//  mowine
//
//  Created by Josh Freed on 3/21/18.
//  Copyright (c) 2018 Josh Freed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WineDetailsPresentationLogic {
    func presentWine(response: WineDetails.FetchWine.Response)
    func presentWineImage(data: Data?)
}

class WineDetailsPresenter: WineDetailsPresentationLogic {
    weak var viewController: WineDetailsDisplayLogic?

    // MARK: Fetch wine

    func presentWine(response: WineDetails.FetchWine.Response) {
        var priceString: String?
        if let price = response.wine.price {
            priceString = String(describing: price)
        }
        let wineViewModel = WineDetails.WineViewModel(
            name: response.wine.name,
            rating: response.wine.rating,
            type: response.wine.type.name,
            variety: response.wine.variety?.name,
            price: priceString,
            whereToBuy: response.wine.location
        )
        let viewModel = WineDetails.FetchWine.ViewModel(wine: wineViewModel)
        viewController?.displayWine(viewModel: viewModel)
    }
    
    func presentWineImage(data: Data?) {
        var photo: UIImage?
        
        if let data = data {
            photo = UIImage(data: data)
        }
        
        viewController?.displayWineImage(photo)
    }
}
