//
//  WineDetailsModels.swift
//  mowine
//
//  Created by Josh Freed on 3/21/18.
//  Copyright (c) 2018 Josh Freed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum WineDetails {
    struct WineViewModel {
        let name: String
        let rating: Double
        let type: String
        let variety: String?
        let price: String?
        let whereToBuy: String?
    }
    
    // MARK: Use cases

    enum FetchWine {
        struct Request {
        }

        struct Response {
            let wine: Wine
        }

        struct ViewModel {
            let wine: WineViewModel
        }
    }
}
