//
//  SignUpInteractor.swift
//  mowine
//
//  Created by Josh Freed on 3/21/18.
//  Copyright (c) 2018 Josh Freed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignUpBusinessLogic {
    func signUp(request: SignUp.SignUp.Request)
}

protocol SignUpDataStore {
    //var name: String { get set }
}

class SignUpInteractor: SignUpBusinessLogic, SignUpDataStore {
    var presenter: SignUpPresentationLogic?
    var worker: SignUpWorker?
    //var name: String = ""

    // MARK: Sign Up

    func signUp(request: SignUp.SignUp.Request) {
        // Make sure password meets the requirements
        // Make sure the email address is unique and is not associated with another account
        // Make sure firstName is not empty
        
        let response = SignUp.SignUp.Response(user: nil, error: nil)
        presenter?.presentSignUp(response: response)
    }
}
