//
//  SignUpViewController.swift
//  mowine
//
//  Created by Josh Freed on 3/21/18.
//  Copyright (c) 2018 Josh Freed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import JFLib

protocol SignUpDisplayLogic: class {
    func displaySignUpResult(viewModel: SignUp.SignUp.ViewModel)
}

class SignUpViewController: UIViewController, SignUpDisplayLogic {
    var interactor: SignUpBusinessLogic?
    var router: (NSObjectProtocol & SignUpRoutingLogic & SignUpDataPassing)?
    
    @IBOutlet weak var scrollView: UIScrollView!
    @IBOutlet weak var firstNameTextField: FloatingLabelTextField!
    @IBOutlet weak var lastNameTextField: FloatingLabelTextField!
    @IBOutlet weak var emailAddressTextField: FloatingLabelTextField!
    @IBOutlet weak var passwordTextField: FloatingLabelTextField!
    @IBOutlet weak var errorMessageLabel: UILabel!
    @IBOutlet weak var signUpButton: ButtonPrimary!
    
    
    // MARK: Object lifecycle

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }

    // MARK: Setup

    private func setup() {
        let viewController = self
        let interactor = SignUpInteractor()
        let presenter = SignUpPresenter()
        let router = SignUpRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        interactor.worker = SignUpWorker()
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }

    // MARK: Routing

    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    @IBAction func tappedSignInButton(_ sender: UIButton) {
        
    }

    // MARK: View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
        
        NotificationCenter.default.addObserver(self, selector: #selector(keyboardWillShow), name: .UIKeyboardWillShow, object: nil)
        NotificationCenter.default.addObserver(self, selector: #selector(keyboardWillHide), name: .UIKeyboardWillHide, object: nil)        
        
        hideErrorLabel()
        
        firstNameTextField.delegate = self
        lastNameTextField.delegate = self
        emailAddressTextField.delegate = self
        passwordTextField.delegate = self
        
        firstNameTextField.becomeFirstResponder()
    }
    
    @objc func keyboardWillShow(notification: Notification) {
        if let keyboardSize = (notification.userInfo?[UIKeyboardFrameBeginUserInfoKey] as? NSValue)?.cgRectValue {
            let kbSize = keyboardSize.size
            let contentInsets = UIEdgeInsetsMake(0.0, 0.0, kbSize.height, 0.0);
            scrollView.contentInset = contentInsets
            scrollView.scrollIndicatorInsets = contentInsets
        }
    }
    
    @objc func keyboardWillHide(notification: Notification) {
        scrollView.contentInset = UIEdgeInsets.zero
        scrollView.scrollIndicatorInsets = UIEdgeInsets.zero
    }
    
    // MARK: Helpers
    
    func hideErrorLabel() {
        errorMessageLabel.isHidden = true
        errorMessageLabel.text = nil
    }
    
    func showErrorLabel(_ error: String) {
        errorMessageLabel.text = error
        errorMessageLabel.isHidden = false
    }

    // MARK: Sign Up
    
    @IBAction func tappedSignUp(_ sender: ButtonPrimary) {
        signUp()
    }
    
    func signUp() {
        hideErrorLabel()
        
        if firstNameTextField.text == nil || firstNameTextField.text!.isEmpty {
            firstNameTextField.displayInvalid()
        }
        
        if emailAddressTextField.text == nil || emailAddressTextField.text!.isEmpty {
            emailAddressTextField.displayInvalid()
        }
        
        if passwordTextField.text == nil || passwordTextField.text!.isEmpty {
            passwordTextField.displayInvalid()
        }
        
        guard
            let firstName = firstNameTextField.text, !firstName.isEmpty,
            let emailAddress = emailAddressTextField.text, !emailAddress.isEmpty,
            let password = passwordTextField.text, !password.isEmpty
        else {
            return
        }
        
        let lastName = lastNameTextField.text
        
        firstNameTextField.displayValid()
        lastNameTextField.displayValid()
        emailAddressTextField.displayValid()
        passwordTextField.displayValid()
        
        signUpButton.displayLoading()
        
        
    }
    
    func displaySignUpResult(viewModel: SignUp.SignUp.ViewModel) {
        
    }
}

extension SignUpViewController: UITextFieldDelegate {
    func textFieldShouldReturn(_ textField: UITextField) -> Bool {
        if textField == firstNameTextField {
            lastNameTextField.becomeFirstResponder()
        } else if textField == lastNameTextField {
            emailAddressTextField.becomeFirstResponder()
        } else if textField == emailAddressTextField {
            passwordTextField.becomeFirstResponder()
        } else if textField == passwordTextField {
            signUp()
        }
        return true
    }
}
