//
//  SignUpPresenter.swift
//  mowine
//
//  Created by Josh Freed on 3/21/18.
//  Copyright (c) 2018 Josh Freed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignUpPresentationLogic {
    func presentSignUp(response: SignUp.SignUp.Response)
}

class SignUpPresenter: SignUpPresentationLogic {
    weak var viewController: SignUpDisplayLogic?

    // MARK: Sign Up

    func presentSignUp(response: SignUp.SignUp.Response) {
        let viewModel = SignUp.SignUp.ViewModel()
        viewController?.displaySignUpResult(viewModel: viewModel)
    }
}
