//
//  SignUpWorker.swift
//  mowine
//
//  Created by Josh Freed on 3/21/18.
//  Copyright (c) 2018 Josh Freed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Model

class SignUpWorker {
    let emailAuthService: EmailAuthenticationService
    let userRepository: UserRepository
    let session: Session
    
    init(
        emailAuthService: EmailAuthenticationService,
        userRepository: UserRepository,
        session: Session
    ) {
        self.emailAuthService = emailAuthService
        self.userRepository = userRepository
        self.session = session
    }
    
    func signUp(emailAddress: String, password: String, fullName: String) async throws {
        try await emailAuthService.signUp(emailAddress: emailAddress, password: password)

        guard let currentUserId = session.currentUserId else {
            throw SessionError.notLoggedIn
        }

        guard try await userRepository.getUserById(currentUserId) == nil else {
            return
        }

        var user = User(id: currentUserId, emailAddress: emailAddress)
        user.fullName = fullName
        try await userRepository.add(user: user)
    }
}
