//
//  SignUpRouter.swift
//  mowine
//
//  Created by Josh Freed on 3/21/18.
//  Copyright (c) 2018 Josh Freed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SignUpRoutingLogic {
    func routeToSignedIn()
}

protocol SignUpDataPassing {
    var dataStore: SignUpDataStore? { get }
}

class SignUpRouter: NSObject, SignUpRoutingLogic, SignUpDataPassing {
    weak var viewController: SignUpViewController?
    var dataStore: SignUpDataStore?

    // MARK: Routing

    func routeToSignedIn() {
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let destinationVC = storyboard.instantiateInitialViewController() as! TabBarViewController
        navigateToSignedIn(source: viewController!, destination: destinationVC)
    }

    // MARK: Navigation

    func navigateToSignedIn(source: SignUpViewController, destination: TabBarViewController) {
        let appDelegate = UIApplication.shared.delegate as! AppDelegate
        appDelegate.window?.rootViewController = destination
    }

    // MARK: Passing data

    //func passDataToSomewhere(source: SignUpDataStore, destination: inout SomewhereDataStore)
    //{
    //  destination.name = source.name
    //}
}
