//
//  AddWineModels.swift
//  mowine
//
//  Created by Josh Freed on 1/7/17.
//  Copyright (c) 2017 BleepSmazz. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct AddWine {

    struct FetchForm {

        struct Request {
        }

        struct Response {
            var wineTypes: [Type]
        }

        struct ViewModel {
            var types: [WineType]
            
            struct WineType: Equatable, CustomStringConvertible {
                var name: String
                var varieties: [String]
                var description: String {
                    return name
                }
                
                public static func ==(lhs: WineType, rhs: WineType) -> Bool {
                    return lhs.name == rhs.name
                }
            }
        }

    }
    
    struct SaveWine {
        struct Request {
            
        }
        
        struct Response {
            
        }
        
        struct ViewModel {
            
        }
    }

}
