//
//  AddWineWorker.swift
//  mowine
//
//  Created by Josh Freed on 1/7/17.
//  Copyright (c) 2017 BleepSmazz. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import CoreData

class AddWineWorker {
    let context: NSManagedObjectContext
    let varietyTranslator: VarietyTranslator
    
    init(context: NSManagedObjectContext, varietyTranslator: VarietyTranslator) {
        self.context = context
        self.varietyTranslator = varietyTranslator
    }
    
    // MARK: - Business Logic

    func createWine(request: AddWine.SaveWine.Request) throws -> Wine {
        let wine = NSEntityDescription.insertNewObject(forEntityName: "Wine", into: context) as! Wine
        wine.name = request.name
        wine.rating = request.rating
        wine.variety = varietyTranslator.toCoreData(input: request.variety)
        wine.location = request.location
        wine.notes = request.notes        
        
        if let price = request.price {
            wine.price = NSDecimalNumber(value: price)
        }
        
        let imageWorker = WineImageWorker()
        if let image = request.image {
            wine.image = imageWorker.convertToPNGData(image: image)
            wine.thumbnail = imageWorker.createThumbnail(from: image)
        }
        
        for foodName in request.pairings {
            let food = NSEntityDescription.insertNewObject(forEntityName: "Food", into: context) as! Food
            food.name = foodName
            wine.addToPairings(food)
        }
        
        try wine.managedObjectContext?.save()

        return wine
    }
}
