//
//  AddWineConfigurator.swift
//  mowine
//
//  Created by Josh Freed on 1/7/17.
//  Copyright (c) 2017 BleepSmazz. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension AddWineViewController: AddWinePresenterOutput {
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router.passDataToNextScene(segue: segue)
    }
}

extension AddWineInteractor: AddWineViewControllerOutput {
}

extension AddWinePresenter: AddWineInteractorOutput {
}

class AddWineConfigurator {
    // MARK: - Object lifecycle

    static let sharedInstance = AddWineConfigurator()

    private init() {
    }

    // MARK: - Configuration

    func configure(viewController: AddWineViewController) {
        let router = AddWineRouter()
        router.viewController = viewController

        let presenter = AddWinePresenter()
        presenter.output = viewController

        let interactor = AddWineInteractor()
        interactor.output = presenter

        viewController.output = interactor
        viewController.router = router
    }
}
