//
//  WineCellarListPresenter.swift
//  mowine
//
//  Created by Josh Freed on 3/20/18.
//  Copyright (c) 2018 Josh Freed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WineCellarListPresentationLogic {
    func presentCellarName(response: WineCellarList.GetCellarName.Response)
    func presentWines(response: WineCellarList.FetchWines.Response)
}

class WineCellarListPresenter: WineCellarListPresentationLogic {
    weak var viewController: WineCellarListDisplayLogic?

    // MARK: Get cellar name
    
    func presentCellarName(response: WineCellarList.GetCellarName.Response) {
        var cellarName = "Cellar"
        if let firstName = response.firstName {
            cellarName = "\(firstName)'s Cellar"
        }        
        let viewModel = WineCellarList.GetCellarName.ViewModel(cellarName: cellarName)
        viewController?.displayCellarName(viewModel: viewModel)
    }
    
    // MARK: Fetch wines

    func presentWines(response: WineCellarList.FetchWines.Response) {
        let wines = response.wines.map { WineListViewModel.from(wine: $0) }
        let viewModel = WineCellarList.FetchWines.ViewModel(wines: wines)
        viewController?.displayWines(viewModel: viewModel)
    }
}
