//
//  WineCellarListRouter.swift
//  mowine
//
//  Created by Josh Freed on 3/20/18.
//  Copyright (c) 2018 Josh Freed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol WineCellarListRoutingLogic {
    func routeToWineList(segue: UIStoryboardSegue)
    func routeToWineDetails()
}

protocol WineCellarListDataPassing {
    var dataStore: WineCellarListDataStore? { get }
}

class WineCellarListRouter: NSObject, WineCellarListRoutingLogic, WineCellarListDataPassing {
    weak var viewController: WineCellarListViewController?
    var dataStore: WineCellarListDataStore?

    // MARK: Routing

    func routeToWineList(segue: UIStoryboardSegue) {
        viewController?.wineListViewController = segue.destination as? WineListViewController
        viewController?.wineListViewController.delegate = viewController
        viewController?.wineListViewController.thumbnailFetcher = Container.shared.wineImageWorker
    }
    
    func routeToWineDetails() {
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let destinationVC = storyboard.instantiateViewController(withIdentifier: "WineDetailsViewController") as! WineDetailsViewController
        var destinationDS = destinationVC.interactor as! WineDetailsDataStore
        passDataToWineDetails(source: dataStore!, destination: &destinationDS)
        navigateToWineDetails(source: viewController!, destination: destinationVC)
    }

    // MARK: Navigation

    func navigateToWineDetails(source: WineCellarListViewController, destination: WineDetailsViewController) {
        source.navigationController?.pushViewController(destination, animated: true)
    }

    // MARK: Passing data

    func passDataToWineDetails(source: WineCellarListDataStore, destination: inout WineDetailsDataStore) {
        destination.wine = source.selectedWine
    }
}
