//
//  SignInWorker.swift
//  mowine
//
//  Created by Josh Freed on 2/27/18.
//  Copyright (c) 2018 Josh Freed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class SignInWorker {
    let emailAuth: EmailAuthenticationService
    
    init(emailAuth: EmailAuthenticationService) {
        self.emailAuth = emailAuth
    }
    
    func signIn(emailAddress: String, password: String, completion: @escaping (Result<Bool, Error>) -> ()) {
        emailAuth.signIn(emailAddress: emailAddress, password: password) { result in
            switch result {
            case .success:
                UserDefaults.standard.set(true, forKey: "hasLoggedInBefore")
                completion(.success(true))
            case .failure(let error):
                switch error {
                case EmailAuthenticationErrors.userNotFound: completion(.success(false))
                case EmailAuthenticationErrors.notAuthorized: completion(.success(false))
                default: completion(.failure(error))
                }
            }
        }
    }
}
