//
//  SignInRouter.swift
//  mowine
//
//  Created by Josh Freed on 2/27/18.
//  Copyright (c) 2018 Josh Freed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SignInRoutingLogic {
    func routeToSignedIn()
}

protocol SignInDataPassing {
    var dataStore: SignInDataStore? { get }
}

class SignInRouter: NSObject, SignInRoutingLogic, SignInDataPassing {
    weak var viewController: SignInViewController?
    var dataStore: SignInDataStore?

    // MARK: Routing

    func routeToSignedIn() {
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let destinationVC = storyboard.instantiateViewController(withIdentifier: "TabBarViewController") as! TabBarViewController
        navigateToSignedIn(source: viewController!, destination: destinationVC)
    }
    
    // MARK: Navigation

    func navigateToSignedIn(source: SignInViewController, destination: TabBarViewController) {
        let appDelegate = UIApplication.shared.delegate as! AppDelegate
        appDelegate.window?.rootViewController = destination
    }
    
    // MARK: Passing data

    //func passDataToSomewhere(source: SignInDataStore, destination: inout SomewhereDataStore)
    //{
    //  destination.name = source.name
    //}
}
