//
//  MyWinesWorker.swift
//  mowine
//
//  Created by Josh Freed on 3/15/18.
//  Copyright (c) 2018 Josh Freed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import JFLib

class MyWinesWorker {
    let wineRepository: WineRepository
    
    init(wineRepository: WineRepository) {
        self.wineRepository = wineRepository
    }
    
    func fetchMyWines(completion: @escaping (Result<[Wine]>) -> ()) {
        wineRepository.getMyWines(completion: completion)
    }
}
