//
//  MyWinesRouter.swift
//  mowine
//
//  Created by Josh Freed on 1/7/17.
//  Copyright (c) 2017 BleepSmazz. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol MyWinesRouterInput {
    func navigateToEditWine()
}

class MyWinesRouter: MyWinesRouterInput {
    weak var viewController: MyWinesViewController!

    // MARK: - Navigation

    func navigateToEditWine() {
        viewController.performSegue(withIdentifier: "EditWine", sender: nil)
    }

    // MARK: - Communication

    func passDataToNextScene(segue: UIStoryboardSegue) {
        // NOTE: Teach the router which scenes it can communicate with

        if segue.identifier == "EditWine" {
            passDataToEditWineScene(segue: segue)
        }
    }

    func passDataToEditWineScene(segue: UIStoryboardSegue) {
        let source = segue.source as! MyWinesViewController
        let dest = segue.destination as! EditWineViewController
        dest.output.wine = source.output.selectedWine
    }
}
