//
//  MyWinesViewController.swift
//  mowine
//
//  Created by Josh Freed on 1/7/17.
//  Copyright (c) 2017 BleepSmazz. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol MyWinesViewControllerInput {
    func displaySomething(viewModel: MyWines.Something.ViewModel)
}

protocol MyWinesViewControllerOutput {
    func doSomething(request: MyWines.Something.Request)
}

class MyWinesViewController: UITableViewController, MyWinesViewControllerInput {
    var output: MyWinesViewControllerOutput!
    var router: MyWinesRouter!

    // MARK: - Object lifecycle

    override func awakeFromNib() {
        super.awakeFromNib()
        MyWinesConfigurator.sharedInstance.configure(viewController: self)
    }

    // MARK: - View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
        doSomethingOnLoad()
    }

    // MARK: - Event handling

    func doSomethingOnLoad() {
        // NOTE: Ask the Interactor to do some work

        let request = MyWines.Something.Request()
        output.doSomething(request: request)
    }

    // MARK: - Display logic

    func displaySomething(viewModel: MyWines.Something.ViewModel) {
        // NOTE: Display the result from the Presenter

        // nameTextField.text = viewModel.name
    }
}
