//
//  MyWinesPresenter.swift
//  mowine
//
//  Created by Josh Freed on 1/7/17.
//  Copyright (c) 2017 BleepSmazz. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol MyWinesPresenterInput {
    func presentSomething(response: MyWines.Something.Response)
}

protocol MyWinesPresenterOutput: class {
    func displaySomething(viewModel: MyWines.Something.ViewModel)
}

class MyWinesPresenter: MyWinesPresenterInput {
    weak var output: MyWinesPresenterOutput!

    // MARK: - Presentation logic

    func presentSomething(response: MyWines.Something.Response) {
        // NOTE: Format the response from the Interactor and pass the result back to the View Controller

        let viewModel = MyWines.Something.ViewModel()
        output.displaySomething(viewModel: viewModel)
    }
}
