//
//  MyWinesRouter.swift
//  mowine
//
//  Created by Josh Freed on 3/15/18.
//  Copyright (c) 2018 Josh Freed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MyWinesRoutingLogic {
    func routeToEditWine(segue: UIStoryboardSegue)
}

protocol MyWinesDataPassing {
    var dataStore: MyWinesDataStore? { get }
}

class MyWinesRouter: NSObject, MyWinesRoutingLogic, MyWinesDataPassing {
    weak var viewController: MyWinesViewController?
    var dataStore: MyWinesDataStore?

    // MARK: Routing

    func routeToEditWine(segue: UIStoryboardSegue) {
        let destinationVC = segue.destination as! EditWineViewController
        destinationVC.output.wine = dataStore?.selectedWine
    }
    
    // MARK: Navigation

    //func navigateToSomewhere(source: MyWinesViewController, destination: SomewhereViewController)
    //{
    //  source.show(destination, sender: nil)
    //}

    // MARK: Passing data

//    func passDataToSomewhere(source: MyWinesDataStore, destination: inout EditWineViewController)
//    {
//        destination.output.wine = source.selectedWine
//    }
}
