//
//  MyWinesModels.swift
//  mowine
//
//  Created by Josh Freed on 1/7/17.
//  Copyright (c) 2017 BleepSmazz. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct MyWines {

    struct FetchMyWines {

        struct Request {
        }

        struct Response {
            var wines: [Wine]
        }

        struct ViewModel {
            var wines: [WineViewModel]
            
            struct WineViewModel: Equatable {
                var id: String
                var thumbnail: UIImage?
                var name: String
                var variety: String
                var rating: Double
                
                public static func ==(lhs: WineViewModel, rhs: WineViewModel) -> Bool {
                    return lhs.id == rhs.id
                }
            }
        }

    }

}
