//
//  MyWinesWorker.swift
//  mowine
//
//  Created by Josh Freed on 3/15/18.
//  Copyright (c) 2018 Josh Freed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import JFLib

class MyWinesWorker {
    let wineRepository: WineRepository
    let session: Session
    let imageWorker: WineImageWorker
    
    init(wineRepository: WineRepository, session: Session, imageWorker: WineImageWorker) {
        self.wineRepository = wineRepository
        self.session = session
        self.imageWorker = imageWorker
    }
    
    func fetchMyWines(completion: @escaping (Result<[Wine]>) -> ()) {
        guard let currentUserId = session.currentUserId else {
            completion(.failure(MoWineError.notLoggedIn))
            return
        }
        wineRepository.getWines(userId: currentUserId) { result in
            switch result {
            case .success(let wines):
                let sorted = wines.sorted(by: { $0.createdAt > $1.createdAt })
                completion(.success(sorted))
            case .failure(let error):
                completion(.failure(error))
            }
        }
    }
    
    func fetchThumbnail(wine: Wine, completion: @escaping (Result<Data?>) -> ()) {
        imageWorker.fetchThumbnail(for: wine, completion: completion)
    }
}
