//
//  MyWinesInteractor.swift
//  mowine
//
//  Created by Josh Freed on 1/7/17.
//  Copyright (c) 2017 BleepSmazz. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol MyWinesInteractorInput {
    func fetchMyWines(request: MyWines.FetchMyWines.Request)
}

protocol MyWinesInteractorOutput {
    func presentMyWines(response: MyWines.FetchMyWines.Response)
}

class MyWinesInteractor: MyWinesInteractorInput {
    var output: MyWinesInteractorOutput!
    let worker = MyWinesWorker()

    // MARK: - Business logic

    func fetchMyWines(request: MyWines.FetchMyWines.Request) {
        let wines = worker.fetchMyWines()

        let response = MyWines.FetchMyWines.Response(wines: wines)
        output.presentMyWines(response: response)
    }
}
