//
//  FriendsInteractorTests.swift
//  mowine
//
//  Created by Josh Freed on 3/7/18.
//  Copyright (c) 2018 Josh Freed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import mowine
import XCTest
import JFLib
import Nimble

class FriendsInteractorTests: XCTestCase {
    // MARK: Subject under test

    var sut: FriendsInteractor!
    let worker = MockFriendsWorker()
    let spy = FriendsPresentationLogicSpy()

    // MARK: Test lifecycle

    override func setUp() {
        super.setUp()
        setupFriendsInteractor()
    }

    override func tearDown() {
        super.tearDown()
    }

    // MARK: Test setup

    func setupFriendsInteractor() {
        sut = FriendsInteractor(worker: worker)
        sut.presenter = spy
    }

    // MARK: Test doubles

    class FriendsPresentationLogicSpy: FriendsPresentationLogic {
        var presentFriendsCalled = false
        var presentFriendsResponse: Friends.FetchFriends.Response?
        func presentFriends(response: Friends.FetchFriends.Response) {
            presentFriendsCalled = true
            presentFriendsResponse = response
        }
        
        var presentEmptySearchCalled = false
        func presentEmptySearch() {
            presentEmptySearchCalled = true
        }
        
        var presentLoadingSearchResultsCalled = false
        func presentLoadingSearchResults() {
            presentLoadingSearchResultsCalled = true
        }
        
        var presentSearchResultsCalled = false
        var presentSearchResultsCallCount = 0
        var presentSearchResultsResponse: Friends.SearchUsers.Response?
        func presentSearchResults(response: Friends.SearchUsers.Response) {
            presentSearchResultsCallCount += 1
            presentSearchResultsCalled = true
            presentSearchResultsResponse = response
        }
        
        var presentAddFriendCalled = false
        func presentAddFriend(response: Friends.AddFriend.Response) {
            presentAddFriendCalled = true
        }
        
        var presentAddFriendErrorCalled = false
        func presentAddFriendError(response: Friends.AddFriend.Response) {
            presentAddFriendErrorCalled = true
        }

        func presentSelectedUser(response: Friends.SelectUser.Response) {

        }
    }
    
    class MockFriendsWorker: FriendsWorker {
        init() {
            super.init(userRepository: MockUserRepository(), session: MockSession())
        }

        var fetchMyFriendsResult: Result<[User]>?
        override func fetchMyFriends(completion: @escaping (Result<[User]>) -> ()) {
            if let result = fetchMyFriendsResult {
                completion(result)
            }
        }
        
        var searchUsersDelay: Double = 0
        var searchUsers_searchString: String?
        var searchUsersCallCount = 0
        private var searchUsersResults: [Int: Result<[User]>] = [:]
        override func searchUsers(searchString: String, completion: @escaping (Result<[User]>) -> ()) {
            searchUsersCallCount += 1
            searchUsers_searchString = searchString
            if let result = searchUsersResults[searchUsersCallCount] {
                if searchUsersDelay > 0 {
                    delay(seconds: searchUsersDelay) {
                        completion(result)
                    }
                } else {
                    completion(result)
                }
            }
        }
        
        func mockSearchUsers(result: Result<[User]>) {
            searchUsersResults[1] = result
        }
        
        func mockSearchUsers(callCount: Int, result: Result<[User]>) {
            searchUsersResults[callCount] = result
        }
        
        var addFriendResult: Result<User>?
        var addFriendCalled = false
        var addFriendUserId: UserId?
        override func addFriend(userId: UserId, completion: @escaping (Result<User>) -> ()) {
            addFriendCalled = true
            addFriendUserId = userId
            if let result = addFriendResult {
                completion(result)
            }
        }
        
        func verifyAddFriendCalled(userId: UserId) {
            expect(self.addFriendCalled).to(beTrue())
            expect(self.addFriendUserId).to(equal(userId))
        }
    }

    // MARK: Fetch friends

    func testFetchFriends() {
        // Given
        let friend1 = UserBuilder.aUser().build()
        let friend2 = UserBuilder.aUser().build()
        let friends = [friend1, friend2]
        worker.fetchMyFriendsResult = .success(friends)
        let request = Friends.FetchFriends.Request()

        // When
        sut.fetchFriends(request: request)

        // Then
        XCTAssertTrue(spy.presentFriendsCalled, "fetchFriends(request:) should ask the presenter to format the result")
        expect(self.spy.presentFriendsResponse?.friends).to(equal(friends))
        expect(self.sut.friends).to(equal(friends))
    }

    // MARK: Add friend
    
    func testAddFriend() {
        // Given
        let user = UserBuilder.aUser().build()
        let userId = user.id
        let request = Friends.AddFriend.Request(userId: String(describing: userId))
        worker.addFriendResult = .success(user)
        
        // When
        sut.addFriend(request: request)
        
        // Then
        worker.verifyAddFriendCalled(userId: userId)
        expect(self.spy.presentAddFriendCalled).to(beTrue())
        expect(self.sut.friends).to(contain(user))
    }
    
    // Can no longer easily tell when a user id is invalid. Perhaps check for empty string?
//    func testAddFriendFailsIfGivenInvalidUserId() {
//        // Given
//        let request = Friends.AddFriend.Request(userId: "not a uuid")
//
//        // When
//        sut.addFriend(request: request)
//
//        // Then
//        expect(self.worker.addFriendCalled).to(beFalse())
//        expect(self.spy.presentAddFriendCalled).to(beFalse())
//    }
    
    func testAddFriendShouldPresentAnError() {
        // Given
        let user = UserBuilder.aUser().build()
        let userId = user.id
        let request = Friends.AddFriend.Request(userId: String(describing: userId))
        worker.addFriendResult = .failure(TestingError.someError)
        
        // When
        sut.addFriend(request: request)
        
        // Then
        worker.verifyAddFriendCalled(userId: userId)
        expect(self.spy.presentAddFriendCalled).to(beFalse())
        expect(self.spy.presentAddFriendErrorCalled).to(beTrue())
        expect(self.sut.friends).toNot(contain(user))
    }
    
    // MARK: Search users

    func testSearchUsers_shouldDisplayTheSearchResults() {
        // Given
        let user1 = UserBuilder.aUser().build()
        let user2 = UserBuilder.aUser().build()
        worker.mockSearchUsers(result: .success([user1, user2]))
        let request = Friends.SearchUsers.Request(searchString: "momo")
        
        // When
        sut.searchUsers(request: request)
        
        // Then
        expect(self.worker.searchUsers_searchString).toEventually(equal("momo"))
        expect(self.spy.presentSearchResultsCalled).toEventually(beTrue())
        expect(self.spy.presentSearchResultsResponse?.matches).toEventually(equal([user1, user2]))
    }
    
    func testSearchUsers_shouldReturnAnEmptySearchWhenTheSearchStringIsBlank() {
        // Given
        let request = Friends.SearchUsers.Request(searchString: "")
        
        // When
        sut.searchUsers(request: request)
        
        // Then
        expect(self.spy.presentEmptySearchCalled).to(beTrue())
        expect(self.spy.presentLoadingSearchResultsCalled).to(beFalse())
        expect(self.spy.presentSearchResultsCalled).to(beFalse())
    }
    
    func testSearchUser_shouldOnlySearchOnceIfCalledMultipleTimeWithinTheQuietPeriod() {
        // Given
        let user1 = UserBuilder.aUser().build()
        let user2 = UserBuilder.aUser().build()
        worker.mockSearchUsers(callCount: 1, result: .success([user1, user2]))
        worker.mockSearchUsers(callCount: 2, result: .success([user1, user2]))
        let request = Friends.SearchUsers.Request(searchString: "momo")

        // When
        sut.searchUsers(request: request)
        sut.searchUsers(request: request)
        
        // Then
        expect(self.spy.presentSearchResultsCallCount).toEventually(equal(1))
    }
    
    func testSearchUser_shouldNotPresentResultForACancelledSearch() {
        // Given
        let user1 = UserBuilder.aUser().withEmail("u1@test.com").build()
        let user2 = UserBuilder.aUser().withEmail("u2@test.com").build()
        let user3 = UserBuilder.aUser().withEmail("u3@test.com").build()
        let user4 = UserBuilder.aUser().withEmail("u4@test.com").build()
        let request1 = Friends.SearchUsers.Request(searchString: "mo")
        let request2 = Friends.SearchUsers.Request(searchString: "momo")
        worker.searchUsersDelay = 1
        worker.mockSearchUsers(callCount: 1, result: .success([user1, user2]))
        worker.mockSearchUsers(callCount: 2, result: .success([user3, user4]))
        
        // When
        sut.searchUsers(request: request1)
        sut.searchTimer?.fire()
        sut.searchUsers(request: request2)
        
        // Then
        expect(self.spy.presentSearchResultsCallCount).toEventually(equal(1), timeout: 3, pollInterval: 3)
        expect(self.spy.presentSearchResultsResponse?.matches).to(equal([user3, user4]))
    }

    // MARK: Cancel search

    func testCancelSearch_displaysFriendsList() {
        // Given
        sut.displayMode = .search
        sut.friends = [
            UserBuilder.aUser().build(),
            UserBuilder.aUser().build(),
        ]

        // When
        sut.cancelSearch()

        // Then
        expect(self.sut.displayMode).to(equal(FriendsInteractor.DisplayMode.friends))
        expect(self.spy.presentFriendsCalled).to(beTrue())
        expect(self.spy.presentFriendsResponse?.friends).to(equal(sut.friends))
    }

    func testCancelSearch_cancelsPendingSearchTimer() {
        // Given
        sut.searchTimer = Timer.scheduledTimer(withTimeInterval: 5, repeats: false) { timer in
            fail("Timer should not have been fired")
        }

        // When
        sut.cancelSearch()

        // Then
        expect(self.sut.searchTimer).to(beNil())
    }
    
    func testCancelSearch_clearsSearchesInProgress() {
        // Given
        sut.searches = [UUID()]

        // When
        sut.cancelSearch()

        // Then
        expect(self.sut.searches).to(beEmpty())
    }

    // MARK: Friend was added

    func testFriendWasAdded() {
        // Given
        let friend = UserBuilder.aUser().build()

        // When
        NotificationCenter.default.post(name: .friendAdded, object: nil, userInfo: ["friend": friend])

        // Then
        expect(self.sut.friends).to(contain(friend))
    }
    
    func testFriendWasAdded_presentsFriendsIfNotSearching() {
        // Given
        let friend = UserBuilder.aUser().build()
        sut.displayMode = .friends

        // When
        NotificationCenter.default.post(name: .friendAdded, object: nil, userInfo: ["friend": friend])

        // Then
        expect(self.spy.presentFriendsCalled).to(beTrue())
        expect(self.spy.presentSearchResultsCalled).to(beFalse())
    }

    func testFriendWasAdded_doesPresentsUpdatedSearchResultsIfSearching() {
        // Given
        let friend = UserBuilder.aUser().build()
        sut.displayMode = .search

        // When
        NotificationCenter.default.post(name: .friendAdded, object: nil, userInfo: ["friend": friend])

        // Then
        expect(self.spy.presentFriendsCalled).to(beFalse())
        expect(self.spy.presentSearchResultsCalled).to(beTrue())
    }

    // MARK: friend was removed

    func testFriendWasRemoved() {
        // Given
        let friend = UserBuilder.aUser().build()
        sut.friends.append(friend)

        // When
        NotificationCenter.default.post(name: .friendRemoved, object: nil, userInfo: ["friendId": friend.id])

        // Then
        expect(self.sut.friends).toNot(contain(friend))
    }

    func testFriendWasRemoved_refreshFriendList() {
        // Given
        let friend = UserBuilder.aUser().build()
        sut.friends.append(friend)
        sut.displayMode = .friends

        // When
        NotificationCenter.default.post(name: .friendRemoved, object: nil, userInfo: ["friendId": friend.id])

        // Then
        expect(self.spy.presentFriendsCalled).to(beTrue())
        expect(self.spy.presentSearchResultsCalled).to(beFalse())
    }

    func testFriendWasRemoved_refreshSearchResults() {
        // Given
        let friend = UserBuilder.aUser().build()
        sut.friends.append(friend)
        sut.lastSearchResults = [UserBuilder.aUser().build(), friend]
        sut.displayMode = .search

        // When
        NotificationCenter.default.post(name: .friendRemoved, object: nil, userInfo: ["friendId": friend.id])

        // Then
        expect(self.spy.presentFriendsCalled).to(beFalse())
        expect(self.spy.presentSearchResultsCalled).to(beTrue())
    }
}


