//
//  FriendsPresenterTests.swift
//  mowine
//
//  Created by Josh Freed on 3/7/18.
//  Copyright (c) 2018 Josh Freed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import mowine
import XCTest

class FriendsPresenterTests: XCTestCase {
    // MARK: Subject under test

    var sut: FriendsPresenter!

    // MARK: Test lifecycle

    override func setUp() {
        super.setUp()
        setupFriendsPresenter()
    }

    override func tearDown() {
        super.tearDown()
    }

    // MARK: Test setup

    func setupFriendsPresenter() {
        sut = FriendsPresenter()
    }

    // MARK: Test doubles

    class FriendsDisplayLogicSpy: FriendsDisplayLogic {
        var displayFriendsCalled = false
        func displayFriends(viewModel: Friends.FetchFriends.ViewModel) {
            displayFriendsCalled = true
        }
        
        func displaySearchResults(viewModel: Friends.SearchUsers.ViewModel) {
            
        }
    }

    // MARK: Tests

    func testPresentFriends() {
        // Given
        let spy = FriendsDisplayLogicSpy()
        sut.viewController = spy
        let response = Friends.FetchFriends.Response(friends: [])

        // When
        sut.presentFriends(response: response)

        // Then
        XCTAssertTrue(spy.displayFriendsCalled, "presentSomething(response:) should ask the view controller to display the result")
    }
}
