//
//  FriendsInteractorTests.swift
//  mowine
//
//  Created by Josh Freed on 3/7/18.
//  Copyright (c) 2018 Josh Freed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import mowine
import XCTest
import JFLib

class FriendsInteractorTests: XCTestCase {
    // MARK: Subject under test

    var sut: FriendsInteractor!
    let worker = MockFriendsWorker()
    let spy = FriendsPresentationLogicSpy()

    // MARK: Test lifecycle

    override func setUp() {
        super.setUp()
        setupFriendsInteractor()
    }

    override func tearDown() {
        super.tearDown()
    }

    // MARK: Test setup

    func setupFriendsInteractor() {
        sut = FriendsInteractor()
        sut.worker = worker
        sut.presenter = spy
    }

    // MARK: Test doubles

    class FriendsPresentationLogicSpy: FriendsPresentationLogic {
        var presentFriendsCalled = false

        func presentFriends(response: Friends.FetchFriends.Response) {
            presentFriendsCalled = true
        }
        
        func presentSearchResults(response: Friends.SearchUsers.Response) {
            
        }
    }
    
    class MockFriendsWorker: FriendsWorker {
        init() {
            super.init(userRepository: MockUserRepository(), session: MockSession())
        }
        
        var fetchMyFriendsResult: Result<[User]>?
        override func fetchMyFriends(completion: @escaping (Result<[User]>) -> ()) {
            if let result = fetchMyFriendsResult {
                completion(result)
            }
        }
        
        override func searchUsers(searchString: String, completion: @escaping (Result<[User]>) -> ()) {
            
        }
    }

    // MARK: Tests

    func testFetchFriends() {
        // Given
        let request = Friends.FetchFriends.Request()
        worker.fetchMyFriendsResult = .success([])

        // When
        sut.fetchFriends(request: request)

        // Then
        XCTAssertTrue(spy.presentFriendsCalled, "fetchFriends(request:) should ask the presenter to format the result")
    }
}
