//
//  SelectTypePresenter.swift
//  mowine
//
//  Created by Josh Freed on 7/4/17.
//  Copyright (c) 2017 BleepSmazz. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SelectTypePresentationLogic {
    func presentSelectedType(response: SelectType.SelectType.Response)
}

class SelectTypePresenter: SelectTypePresentationLogic {
    weak var viewController: SelectTypeDisplayLogic?

    // MARK: Select wine type

    func presentSelectedType(response: SelectType.SelectType.Response) {
        let viewModel = SelectType.SelectType.ViewModel(hasVarieties: response.type.varieties.count > 0)
        viewController?.displaySelectedType(viewModel: viewModel)
    }
}
