//
//  RateWinePresenter.swift
//  mowine
//
//  Created by Josh Freed on 9/20/17.
//  Copyright (c) 2017 BleepSmazz. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RateWinePresentationLogic {
    func presentSomething(response: RateWine.Something.Response)
}

class RateWinePresenter: RateWinePresentationLogic {
    weak var viewController: RateWineDisplayLogic?

    // MARK: Do something

    func presentSomething(response: RateWine.Something.Response) {
        let viewModel = RateWine.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
