//
//  RateWineInteractor.swift
//  mowine
//
//  Created by Josh Freed on 9/20/17.
//  Copyright (c) 2017 BleepSmazz. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RateWineBusinessLogic {
    func getWine(request: RateWine.GetWine.Request)
}

protocol RateWineDataStore {
    var wineType: Type! { get set }
    var variety: Variety! { get set }
    var photo: UIImage? { get set }
    var name: String { get set }
}

class RateWineInteractor: RateWineBusinessLogic, RateWineDataStore {
    var presenter: RateWinePresentationLogic?
    var worker: RateWineWorker?
    var wineType: Type!
    var variety: Variety!
    var photo: UIImage?
    var name: String = ""

    // MARK: Get wine

    func getWine(request: RateWine.GetWine.Request) {
        let response = RateWine.GetWine.Response(photo: photo, name: name)
        presenter?.presentWine(response: response)
    }
}
