//
//  WineCellarWorker.swift
//  mowine
//
//  Created by Josh Freed on 3/15/18.
//  Copyright (c) 2018 Josh Freed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import JFLib

class WineCellarWorker {
    let wineTypeRepository: WineTypeRepository
    let userRepository: UserRepository
    
    init(wineTypeRepository: WineTypeRepository, userRepository: UserRepository) {
        self.wineTypeRepository = wineTypeRepository
        self.userRepository = userRepository
    }
    
    func getUser(by userId: UserId, completion: @escaping (Result<User?>) -> ()) {
        userRepository.getUserById(userId, completion: completion)
    }
    
    func getWineTypes(completion: @escaping (Result<[WineType]>) -> ()) {
        wineTypeRepository.getAll(completion: completion)
    }
}
