//
//  WineCellarModels.swift
//  mowine
//
//  Created by Josh Freed on 3/15/18.
//  Copyright (c) 2018 Josh Freed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Model

enum WineCellar {
    // MARK: Use cases

    enum GetWineTypes {
        struct Request {
        }

        struct Response {
            var types: [WineType]
        }

        struct ViewModel {
            var types: [String]
        }
    }
    
    enum SelectType {
        struct Request {
            var type: String
        }
        
        struct Response {
            var type: WineType?
        }
        
        struct ViewModel {            
        }
    }
}
