//
//  WineCellarViewController.swift
//  mowine
//
//  Created by Josh Freed on 3/15/18.
//  Copyright (c) 2018 Josh Freed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WineCellarDisplayLogic: class {
    func displayWineTypes(viewModel: WineCellar.GetWineTypes.ViewModel)
    func displaySelectedType(viewModel: WineCellar.SelectType.ViewModel)
}
