//
//  WineCellarPresenter.swift
//  mowine
//
//  Created by Josh Freed on 3/15/18.
//  Copyright (c) 2018 Josh Freed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WineCellarPresentationLogic {
    func presentWineTypes(response: WineCellar.GetWineTypes.Response)
    func presentSelectedType(response: WineCellar.SelectType.Response)
}

class WineCellarPresenter: WineCellarPresentationLogic {
    weak var viewController: WineCellarDisplayLogic?

    // MARK: Get wine types

    func presentWineTypes(response: WineCellar.GetWineTypes.Response) {
        let types = response.types.map { $0.name }
        let viewModel = WineCellar.GetWineTypes.ViewModel(types: types)
        viewController?.displayWineTypes(viewModel: viewModel)
    }
    
    // MARK: Select type
    
    func presentSelectedType(response: WineCellar.SelectType.Response) {
        let viewModel = WineCellar.SelectType.ViewModel()
        viewController?.displaySelectedType(viewModel: viewModel)
    }
}
