//
//  TopWinesModels.swift
//  mowine
//
//  Created by Josh Freed on 3/14/18.
//  Copyright (c) 2018 Josh Freed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum TopWines {
    // MARK: Use cases

    enum FetchTopWines {
        struct Request {
        }

        struct Response {
            var wines: [Wine]
        }

        struct ViewModel {
            var wines: [WineListViewModel]
        }
    }
}
