//
//  TopWinesPresenter.swift
//  mowine
//
//  Created by Josh Freed on 3/14/18.
//  Copyright (c) 2018 Josh Freed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TopWinesPresentationLogic {
    func presentTopWines(response: TopWines.FetchTopWines.Response)
}

class TopWinesPresenter: TopWinesPresentationLogic {
    weak var viewController: TopWinesDisplayLogic?

    // MARK: Fetch top wines

    func presentTopWines(response: TopWines.FetchTopWines.Response) {
        let wines = response.wines.map { makeWineViewModel(from: $0) }
        let viewModel = TopWines.FetchTopWines.ViewModel(wines: wines)
        viewController?.displayTopWines(viewModel: viewModel)
    }
    
    // MARK: Helpers
    
    private func makeWineViewModel(from model: Wine) -> WineListViewModel {
        var image: UIImage? = nil
        if let thumbnail = model.thumbnail {
            image = UIImage(data: thumbnail)
        }
        return WineListViewModel(name: model.name, rating: model.rating, type: model.varietyName, thumbnail: image)
    }
}
