//
//  TopWinesPresenter.swift
//  mowine
//
//  Created by Josh Freed on 3/14/18.
//  Copyright (c) 2018 Josh Freed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TopWinesPresentationLogic {
    func presentTopWines(response: TopWines.FetchTopWines.Response)
    func presentSelectedWine(response: TopWines.SelectWine.Response)
}

class TopWinesPresenter: TopWinesPresentationLogic {
    weak var viewController: TopWinesDisplayLogic?

    // MARK: Fetch top wines

    func presentTopWines(response: TopWines.FetchTopWines.Response) {
        let wines = response.wines.map { makeWineViewModel(from: $0) }
        let viewModel = TopWines.FetchTopWines.ViewModel(wines: wines)
        viewController?.displayTopWines(viewModel: viewModel)
    }
    
    func presentSelectedWine(response: TopWines.SelectWine.Response) {
        let viewModel = TopWines.SelectWine.ViewModel()
        viewController?.displaySelectedWine(viewModel: viewModel)
    }
    
    // MARK: Helpers
    
    private func makeWineViewModel(from model: Wine) -> WineListViewModel {
        return WineListViewModel.from(wine: model)
    }
}
