//
//  NameWinePresenter.swift
//  mowine
//
//  Created by Josh Freed on 8/11/17.
//  Copyright (c) 2017 BleepSmazz. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NameWinePresentationLogic {
    func presentPhotoPreview(response: NameWine.GetPhotoPreview.Response)
    func presentName(response: NameWine.UpdateName.Response)
    func presentRating(response: NameWine.UpdateRating.Response)
}

class NameWinePresenter: NameWinePresentationLogic {
    weak var viewController: NameWineDisplayLogic?

    // MARK: Get photo preview

    func presentPhotoPreview(response: NameWine.GetPhotoPreview.Response) {
        let viewModel = NameWine.GetPhotoPreview.ViewModel(photo: response.photo)
        viewController?.displayPhotoPreview(viewModel: viewModel)
    }
    
    // MARK: Update name
    
    func presentName(response: NameWine.UpdateName.Response) {
        let viewModel = NameWine.UpdateName.ViewModel()
        viewController?.displayName(viewModel: viewModel)
    }
    
    // MARK: Update rating
    
    func presentRating(response: NameWine.UpdateRating.Response) {
        let viewModel = NameWine.UpdateRating.ViewModel()
        viewController?.displayRating(viewModel: viewModel)
    }
}
