//
//  NameWineModels.swift
//  mowine
//
//  Created by Josh Freed on 8/11/17.
//  Copyright (c) 2017 BleepSmazz. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum NameWine {
    // MARK: Use cases

    enum GetPhotoPreview {

        struct Request {
        }

        struct Response {
            var photo: UIImage?
        }

        struct ViewModel {
            var photo: UIImage?
        }

    }

    enum UpdateName {
        struct Request {
            var name: String?
        }
        
        struct Response {
            
        }
        
        struct ViewModel {
            
        }
    }
}
