//
//  NameWineInteractor.swift
//  mowine
//
//  Created by Josh Freed on 8/11/17.
//  Copyright (c) 2017 BleepSmazz. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NameWineBusinessLogic {
    func getPhotoPreview(request: NameWine.GetPhotoPreview.Request)
}

protocol NameWineDataStore {
    var wineType: Type! { get set }
    var variety: Variety! { get set }
    var photo: UIImage? { get set }
    var name: String { get }
}

class NameWineInteractor: NameWineBusinessLogic, NameWineDataStore {
    var presenter: NameWinePresentationLogic?
    var worker: NameWineWorker?
    var wineType: Type!
    var variety: Variety!
    var photo: UIImage?
    var name: String = ""

    // MARK: Get photo preview

    func getPhotoPreview(request: NameWine.GetPhotoPreview.Request) {
        let response = NameWine.GetPhotoPreview.Response(photo: photo)
        presenter?.presentPhotoPreview(response: response)
    }
}
