//
//  NameWinePresenter.swift
//  mowine
//
//  Created by Josh Freed on 8/11/17.
//  Copyright (c) 2017 BleepSmazz. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NameWinePresentationLogic {
    func presentWine(response: NameWine.CreateWine.Response)
    func presentErrorCreatingWine(_ error: Error)
}

class NameWinePresenter: NameWinePresentationLogic {
    weak var viewController: NameWineDisplayLogic?

    // MARK: Create wine
    
    func presentWine(response: NameWine.CreateWine.Response) {
        viewController?.displayWineCreated(viewModel: NameWine.CreateWine.ViewModel())
    }
    
    func presentErrorCreatingWine(_ error: Error) {
        let message = "\(error)"
        viewController?.displayErrorCreatingWine(message)
    }
}
