//
//  FriendsViewController.swift
//  mowine
//
//  Created by Josh Freed on 3/6/18.
//  Copyright (c) 2018 Josh Freed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import JFLib

protocol FriendsDisplayLogic: class {
    func displayFriends(viewModel: Friends.FetchFriends.ViewModel)
    func displaySearchResults(viewModel: Friends.SearchUsers.ViewModel)
}

class FriendsViewController: UITableViewController, FriendsDisplayLogic {
    var interactor: FriendsBusinessLogic?
    var router: (NSObjectProtocol & FriendsRoutingLogic & FriendsDataPassing)?

    var searchTimer: Timer?
    
    // MARK: Object lifecycle

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }

    // MARK: Setup

    private func setup() {
        let viewController = self
        let interactor = FriendsInteractor()
        let presenter = FriendsPresenter()
        let router = FriendsRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        interactor.worker = FriendsWorker(
            userRepository: Container.shared.userRepository,
            session: Container.shared.session
        )
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }

    // MARK: Routing

    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }

    // MARK: View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
        
        let searchController = UISearchController(searchResultsController: nil)
        searchController.searchResultsUpdater = self
        searchController.delegate = self
        searchController.obscuresBackgroundDuringPresentation = false
        searchController.searchBar.placeholder = "Search for friends"
        navigationItem.searchController = searchController
        definesPresentationContext = true
        
//        tableView.register(UINib(nibName: "UserTableViewCell", bundle: nil), forCellReuseIdentifier: "UserTableViewCell")
        tableView.tableFooterView = UIView(frame: CGRect.zero)
        
        fetchFriends()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        if #available(iOS 11.0, *) {
            navigationItem.hidesSearchBarWhenScrolling = false
        }
    }
    
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        if #available(iOS 11.0, *) {
            navigationItem.hidesSearchBarWhenScrolling = true
        }
    }
    
    // MARK: - UITableViewDataSource
    
    override func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return displayedUsers.count
    }
    
    override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "FriendCell", for: indexPath) as! UserTableViewCell
        cell.configure(user: displayedUsers[indexPath.row])
        return cell
    }

    // MARK: Fetch friends

    var displayedUsers: [Friends.DisplayedUser] = []
    
    func fetchFriends() {
        let request = Friends.FetchFriends.Request()
        interactor?.fetchFriends(request: request)
    }

    func displayFriends(viewModel: Friends.FetchFriends.ViewModel) {
        displayedUsers = viewModel.friends
        
        if displayedUsers.count > 0 {
            hideEmptyMessage()
        } else {
            showEmptyMessage("You don't have any friends, loser.")
        }
        
        tableView.reloadData()
    }
    
    // MARK: Search users
    
    func searchUsers(searchString: String) {
        let request = Friends.SearchUsers.Request(searchString: searchString)
        interactor?.searchUsers(request: request)
    }
    
    func displaySearchResults(viewModel: Friends.SearchUsers.ViewModel) {
        displayedUsers = viewModel.matches
        
        if displayedUsers.count > 0 {
            hideEmptyMessage()
        } else {
            showEmptyMessage("No users match your search.")
        }        
        
        tableView.reloadData()
    }
}

// MARK: - UISearchResultsUpdating
extension FriendsViewController: UISearchResultsUpdating {
    func updateSearchResults(for searchController: UISearchController) {
        let text = searchController.searchBar.text ?? ""
        
        print("updateSearchResults with text: \(text)")
        
        searchTimer?.invalidate()
        
        if text.isEmpty {
            searchUsers(searchString: text)
        } else {
            searchTimer = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: false, block: { _ in
                self.searchUsers(searchString: text)
            })
        }
    }
}

//MARK: - UISearchControllerDelegate
extension FriendsViewController: UISearchControllerDelegate {
    func willPresentSearchController(_ searchController: UISearchController) {
//        print("willPresentSearchController")
    }
    
    func didPresentSearchController(_ searchController: UISearchController) {
//        print("didPresentSearchController")
    }
    
    func willDismissSearchController(_ searchController: UISearchController) {
//        print("willDismissSearchController")
    }
    
    func didDismissSearchController(_ searchController: UISearchController) {
//        print("didDismissSearchController")
    }
}
