//
//  FriendsWorker.swift
//  mowine
//
//  Created by Josh Freed on 3/6/18.
//  Copyright (c) 2018 Josh Freed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import JFLib

enum FriendsWorkerError: Error {
    case notLoggedIn
}

class FriendsWorker {
    let userRepository: UserRepository
    let session: Session
    
    private(set) var friends: [User] = []
    
    init(userRepository: UserRepository, session: Session) {
        self.userRepository = userRepository
        self.session = session
    }
    
    func fetchMyFriends(completion: @escaping (Result<[User]>) -> ()) {
        guard let currentUserId = session.currentUserId else {
            completion(.failure(FriendsWorkerError.notLoggedIn))
            return
        }
        
        userRepository.getFriendsOf(userId: currentUserId) { result in
            if case let .success(friends) = result {
                self.friends = friends
            }
            completion(result)
        }
    }
    
    func searchUsers(searchString: String, completion: @escaping (Result<[User]>) -> ()) {
        guard let currentUserId = session.currentUserId else {
            completion(.failure(FriendsWorkerError.notLoggedIn))
            return
        }
        
        guard !searchString.isEmpty else {
            completion(.success(friends))
            return
        }
        
        userRepository.searchUsers(searchString: searchString) { result in
            switch result {
            case .success(let users):
                let usersWithoutCurrent = users.filter({ $0.id != currentUserId })
                completion(.success(usersWithoutCurrent))
            case .failure(let error): completion(.failure(error))
            }
        }
    }
    
    func addFriend(userId: UserId, completion: @escaping (EmptyResult) -> ()) {
        guard let currentUserId = session.currentUserId else {
            completion(.failure(FriendsWorkerError.notLoggedIn))
            return
        }
        
        userRepository.addFriend(owningUserId: currentUserId, friendId: userId) { result1 in
            self.fetchFriendUser(userId: userId) { _ in
                completion(result1)
            }
        }
    }
    
    func friendWasAdded(userId: UserId, completion: @escaping (EmptyResult) -> ()) {
        fetchFriendUser(userId: userId) { result in
            switch result {
            case .success: completion(.success)
            case .failure(let error): completion(.failure(error))
            }
        }
    }
    
    func friendWasRemoved(userId: UserId) {
        if let index = friends.index(where: { $0.id == userId }) {
            friends.remove(at: index)
        }
    }
    
    private func fetchFriendUser(userId: UserId, completion: @escaping (Result<User?>) -> ()) {
        self.userRepository.getUserById(userId) { result in
            if case let .success(f) = result, let newFriend = f {
                self.friends.append(newFriend)
            }
            completion(result)
        }
    }
}
