//
//  FriendsPresenter.swift
//  mowine
//
//  Created by Josh Freed on 3/6/18.
//  Copyright (c) 2018 Josh Freed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FriendsPresentationLogic {
    func presentFriends(response: Friends.FetchFriends.Response)
}

class FriendsPresenter: FriendsPresentationLogic {
    weak var viewController: FriendsDisplayLogic?

    // MARK: Fetch friends

    func presentFriends(response: Friends.FetchFriends.Response) {
        let friends: [Friends.DisplayedUser] = response.friends.map {
            let displayed = Friends.DisplayedUser(
                userId: "",
                fullName: $0.fullName,
                profilePicture: $0.profilePicture ?? #imageLiteral(resourceName: "No Profile Picture"),
                isFriend: true
            )
            return displayed
        }
        let viewModel = Friends.FetchFriends.ViewModel(friends: friends)
        viewController?.displayFriends(viewModel: viewModel)
    }
}
