//
//  FriendsInteractor.swift
//  mowine
//
//  Created by Josh Freed on 3/6/18.
//  Copyright (c) 2018 Josh Freed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FriendsBusinessLogic {
    func fetchFriends(request: Friends.FetchFriends.Request)
    func searchUsers(request: Friends.SearchUsers.Request)
    func addFriend(request: Friends.AddFriend.Request)
}

protocol FriendsDataStore {
    
}

class FriendsInteractor: FriendsBusinessLogic, FriendsDataStore {
    var presenter: FriendsPresentationLogic?
    var worker: FriendsWorker?

    // MARK: Fetch Friends

    func fetchFriends(request: Friends.FetchFriends.Request) {        
        worker?.fetchMyFriends() { result in
            switch result {
            case .success(let friends): self.handleFriends(friends: friends)
            case .failure(let error): print("\(error)")
            }
        }
    }
    
    private func handleFriends(friends: [User]) {
        let response = Friends.FetchFriends.Response(friends: friends)
        presenter?.presentFriends(response: response)
    }
    
    // MARK: Search Users
    
    func searchUsers(request: Friends.SearchUsers.Request) {
        worker?.searchUsers(searchString: request.searchString) { result in
            switch result {
            case .success(let users): self.handleSearchResults(users: users)
            case .failure(let error): print("\(error)")
            }
        }
    }
    
    private func handleSearchResults(users: [User]) {
        let response = Friends.SearchUsers.Response(matches: users, myFriends: worker?.friends ?? [])
        presenter?.presentSearchResults(response: response)
    }
    
    // MARK: Add friend
    
    func addFriend(request: Friends.AddFriend.Request) {
        guard let userId = UserId(string: request.userId) else {
            return
        }
        
        worker?.addFriend(userId: userId) { result in
            switch result {
            case .success:
                let response = Friends.AddFriend.Response(userId: request.userId)
                self.presenter?.presentAddFriend(response: response)
            case .failure(let error):
                print("\(error)")
                let response = Friends.AddFriend.Response(userId: request.userId)
                self.presenter?.presentAddFriendError(response: response)
            }
        }
    }
}
