//
//  FriendsRouter.swift
//  mowine
//
//  Created by Josh Freed on 3/6/18.
//  Copyright (c) 2018 Josh Freed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol FriendsRoutingLogic {
    func routeToUserProfile(segue: UIStoryboardSegue)
}

protocol FriendsDataPassing {
    var dataStore: FriendsDataStore? { get }
}

class FriendsRouter: NSObject, FriendsRoutingLogic, FriendsDataPassing {
    weak var viewController: FriendsViewController?
    var dataStore: FriendsDataStore?

    // MARK: Routing

    func routeToUserProfile(segue: UIStoryboardSegue) {
        let destinationVC = segue.destination as! UserProfileViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToUserProfile(source: dataStore!, destination: &destinationDS)

    }
    
    // MARK: Navigation

    //func navigateToSomewhere(source: FriendsViewController, destination: SomewhereViewController)
    //{
    //  source.show(destination, sender: nil)
    //}

    // MARK: Passing data

    func passDataToUserProfile(source: FriendsDataStore, destination: inout UserProfileDataStore)
    {
        destination.userId = source.selectedUserId
    }
}
