//
//  FriendsWorker.swift
//  mowine
//
//  Created by Josh Freed on 3/6/18.
//  Copyright (c) 2018 Josh Freed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import JFLib

class FriendsWorker {
    let userRepository: UserRepository
    let session: Session
    
    private(set) var friends: [User] = []
    
    init(userRepository: UserRepository, session: Session) {
        self.userRepository = userRepository
        self.session = session
    }
    
    func fetchMyFriends(completion: @escaping (Result<[User]>) -> ()) {
        guard let currentUserId = session.currentUserId else {
            return
        }
        
        userRepository.getFriendsOf(userId: currentUserId) { result in
            if case let .success(friends) = result {
                self.friends = friends
            }
            completion(result)
        }
    }
    
    func searchUsers(searchString: String, completion: @escaping (Result<[User]>) -> ()) {
        guard let currentUserId = session.currentUserId else {
            return
        }
        
        guard !searchString.isEmpty else {
            completion(.success(friends))
            return
        }
        
        userRepository.searchUsers(searchString: searchString) { result in
            switch result {
            case .success(let users):
                let usersWithoutCurrent = users.filter({ $0.id != currentUserId })
                completion(.success(usersWithoutCurrent))
            case .failure(let error): completion(.failure(error))
            }
        }
    }
}
