//
//  NameAndRatePresenter.swift
//  mowine
//
//  Created by Josh Freed on 8/11/17.
//  Copyright (c) 2017 BleepSmazz. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NameAndRatePresentationLogic {
    func presentPhotoPreview(response: NameAndRate.GetPhotoPreview.Response)
}

class NameAndRatePresenter: NameAndRatePresentationLogic {
    weak var viewController: NameAndRateDisplayLogic?

    // MARK: Do something

    func presentPhotoPreview(response: NameAndRate.GetPhotoPreview.Response) {
        let viewModel = NameAndRate.GetPhotoPreview.ViewModel(photo: response.photo)
        viewController?.displayPhotoPreview(viewModel: viewModel)
    }
}
