//
//  NameAndRateInteractor.swift
//  mowine
//
//  Created by Josh Freed on 8/11/17.
//  Copyright (c) 2017 BleepSmazz. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NameAndRateBusinessLogic {
    func getPhotoPreview(request: NameAndRate.GetPhotoPreview.Request)
}

protocol NameAndRateDataStore {
    var wineType: Type! { get set }
    var variety: Variety! { get set }
    var photo: UIImage? { get set }
}

class NameAndRateInteractor: NameAndRateBusinessLogic, NameAndRateDataStore {
    var presenter: NameAndRatePresentationLogic?
    var worker: NameAndRateWorker?
    var wineType: Type!
    var variety: Variety!
    var photo: UIImage?

    // MARK: Get photo preview

    func getPhotoPreview(request: NameAndRate.GetPhotoPreview.Request) {
        let response = NameAndRate.GetPhotoPreview.Response(photo: photo)
        presenter?.presentPhotoPreview(response: response)
    }
}
