//
//  SignUpWorkerTests.swift
//  mowine
//
//  Created by Josh Freed on 3/28/18.
//  Copyright (c) 2018 Josh Freed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import mowine
import XCTest

class SignUpWorkerTests: XCTestCase {
    // MARK: Subject under test

    var sut: SignUpWorker!
    let emailAuthService = MockEmailAuthService()
    let userRepository = MockUserRepository()

    // MARK: Test lifecycle

    override func setUp() {
        super.setUp()
        setupSignUpWorker()
    }

    override func tearDown() {
        super.tearDown()
    }

    // MARK: Test setup

    func setupSignUpWorker() {
        sut = SignUpWorker(
            emailAuthService: emailAuthService,
            userRepository: userRepository
        )
    }

    // MARK: Test doubles

    // MARK: Tests

    func testSomething() {
        // Given

        // When

        // Then
    }
}
