//
//  FirstTimeInteractor.swift
//  mowine
//
//  Created by Josh Freed on 3/20/18.
//  Copyright (c) 2018 Josh Freed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import JFLib

protocol FirstTimeBusinessLogic {
    func linkToFacebookLogin(fbToken: String)
}

protocol FirstTimeDataStore {
    
}

class FirstTimeInteractor: FirstTimeBusinessLogic, FirstTimeDataStore {
    var presenter: FirstTimePresentationLogic?
    var worker: FirstTimeWorker?

    // MARK: Login with facebook

    func linkToFacebookLogin(fbToken: String) {
        worker?.loginWithFacebook(token: fbToken) { result in
            switch result {
            case .success: self.createUserFromFacebookInfo()
            case .failure(let error): self.presentFacebookLoginError(error)
            }
        }
    }
    
    func createUserFromFacebookInfo() {
        worker?.createUserFromFacebookInfo { result in
            switch result {
            case .success: self.presentFacebookLogin()
            case .failure(let error): self.presentFacebookLoginError(error)
            }
        }
    }
    
    func presentFacebookLogin() {
        let response = FirstTime.FacebookLogin.Response(error: nil)
        self.presenter?.presentFacebookLogin(response: response)
    }
    
    func presentFacebookLoginError(_ error: Error) {
        print("\(error)")
        let response = FirstTime.FacebookLogin.Response(error: error)
        self.presenter?.presentFacebookLogin(response: response)
    }
}
