//
//  FirstTimeRouter.swift
//  mowine
//
//  Created by Josh Freed on 3/20/18.
//  Copyright (c) 2018 Josh Freed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol FirstTimeRoutingLogic {
    func routeToSignIn(segue: UIStoryboardSegue)
    func routeToSignUp(segue: UIStoryboardSegue)
    func routeToSignedIn()
}

protocol FirstTimeDataPassing {
    var dataStore: FirstTimeDataStore? { get }
}

class FirstTimeRouter: NSObject, FirstTimeRoutingLogic, FirstTimeDataPassing {
    weak var viewController: FirstTimeViewController?
    var dataStore: FirstTimeDataStore?

    // MARK: Routing

    func routeToSignIn(segue: UIStoryboardSegue) {
        
    }
    
    func routeToSignUp(segue: UIStoryboardSegue) {
        
    }
    
    func routeToSignedIn() {
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let destinationVC = storyboard.instantiateViewController(withIdentifier: "TabBarViewController") as! TabBarViewController
        navigateToSignedIn(source: viewController!, destination: destinationVC)
    }

    // MARK: Navigation

    func navigateToSignedIn(source: FirstTimeViewController, destination: TabBarViewController) {
        let appDelegate = UIApplication.shared.delegate as! AppDelegate
        appDelegate.window?.rootViewController = destination
    }

    // MARK: Passing data

    //func passDataToSomewhere(source: FirstTimeDataStore, destination: inout SomewhereDataStore)
    //{
    //  destination.name = source.name
    //}
}
