//
//  FirstTimeWorker.swift
//  mowine
//
//  Created by Josh Freed on 3/20/18.
//  Copyright (c) 2018 Josh Freed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import JFLib

class FirstTimeWorker {
    let facebookService: FacebookAuthenticationService

    init(facebookService: FacebookAuthenticationService) {
        self.facebookService = facebookService
    }

    func loginWithFacebook(completion: @escaping (EmptyResult) -> ()) {
        facebookService.signIn(completion: completion)
    }

    func loginWithGoogle() {

    }
}
