//
//  FirstTimePresenter.swift
//  mowine
//
//  Created by Josh Freed on 3/20/18.
//  Copyright (c) 2018 Josh Freed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FirstTimePresentationLogic {
    func presentFacebookLogin(response: FirstTime.FacebookLogin.Response)
}

class FirstTimePresenter: FirstTimePresentationLogic {
    weak var viewController: FirstTimeDisplayLogic?

    // MARK: Login with facebook

    func presentFacebookLogin(response: FirstTime.FacebookLogin.Response) {
        let viewModel = FirstTime.FacebookLogin.ViewModel(error: response.error)
        viewController?.displayFacebookLogin(viewModel: viewModel)
    }
}
