//
//  FirstTimeInteractor.swift
//  mowine
//
//  Created by Josh Freed on 3/20/18.
//  Copyright (c) 2018 Josh Freed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FirstTimeBusinessLogic {
    func doSomething(request: FirstTime.Something.Request)
}

protocol FirstTimeDataStore {
    //var name: String { get set }
}

class FirstTimeInteractor: FirstTimeBusinessLogic, FirstTimeDataStore {
    var presenter: FirstTimePresentationLogic?
    var worker: FirstTimeWorker?
    //var name: String = ""

    // MARK: Do something

    func doSomething(request: FirstTime.Something.Request) {
        worker = FirstTimeWorker()
        worker?.doSomeWork()

        let response = FirstTime.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
