//
//  FirstTimeWorker.swift
//  mowine
//
//  Created by Josh Freed on 3/20/18.
//  Copyright (c) 2018 Josh Freed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import GoogleSignIn
import SwiftyBeaver

class FirstTimeWorkerImpl: AllSocialSignInWorker {
    let facebookSignInWorker: SocialSignInWorker<FacebookProvider>
    let googleSignInWorker: SocialSignInWorker<GoogleProvider>
    let appleSignInWorker: SocialSignInWorker<AppleProvider>

    init(
        facebookSignInWorker: SocialSignInWorker<FacebookProvider>,
        googleSignInWorker: SocialSignInWorker<GoogleProvider>,
        appleSignInWorker: SocialSignInWorker<AppleProvider>
    ) {
        self.facebookSignInWorker = facebookSignInWorker
        self.googleSignInWorker = googleSignInWorker
        self.appleSignInWorker = appleSignInWorker
    }
    
    func login(token: SocialToken, completion: @escaping (Result<User, Error>) -> ()) {
        if let token = token as? FacebookToken {
            facebookSignInWorker.login(token: token, completion: completion)
        } else if let token = token as? GoogleToken {
            googleSignInWorker.login(token: token, completion: completion)
        } else if let token = token as? AppleToken {
            appleSignInWorker.login(token: token, completion: completion)
        } else {
            fatalError("Unknown token type \(token)")
        }
    }
}

class FakeFirstTimeWorker: AllSocialSignInWorker {
    func login(token: SocialToken, completion: @escaping (Result<User, Error>) -> ()) {
        
    }
}
