//
//  FirstTimeViewController.swift
//  mowine
//
//  Created by Josh Freed on 3/20/18.
//  Copyright (c) 2018 Josh Freed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FirstTimeDisplayLogic: class {
    func displaySomething(viewModel: FirstTime.Something.ViewModel)
}

class FirstTimeViewController: UIViewController, FirstTimeDisplayLogic {
    var interactor: FirstTimeBusinessLogic?
    var router: (NSObjectProtocol & FirstTimeRoutingLogic & FirstTimeDataPassing)?

    // MARK: Object lifecycle

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }

    // MARK: Setup

    private func setup() {
        let viewController = self
        let interactor = FirstTimeInteractor()
        let presenter = FirstTimePresenter()
        let router = FirstTimeRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }

    // MARK: Routing

    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }

    // MARK: View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
        doSomething()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        navigationController?.isNavigationBarHidden = true
    }
    
    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        navigationController?.isNavigationBarHidden = false
    }

    // MARK: Do something

    //@IBOutlet weak var nameTextField: UITextField!

    func doSomething() {
        let request = FirstTime.Something.Request()
        interactor?.doSomething(request: request)
    }

    func displaySomething(viewModel: FirstTime.Something.ViewModel) {
        //nameTextField.text = viewModel.name
    }
    
    // MARK: Continue with email
    
    @IBAction func tappedContinueWithEmail(_ sender: ButtonOutline) {
        if UserDefaults.standard.bool(forKey: "hasLoggedInBefore") {
            performSegue(withIdentifier: "SignIn", sender: nil)
        } else {
            performSegue(withIdentifier: "SignUp", sender: nil)
        }
    }
}
