//
//  FirstTimeInteractor.swift
//  mowine
//
//  Created by Josh Freed on 3/20/18.
//  Copyright (c) 2018 Josh Freed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FirstTimeBusinessLogic {
    func loginWithFacebook(request: FirstTime.FacebookLogin.Request)
}

protocol FirstTimeDataStore {
    
}

class FirstTimeInteractor: FirstTimeBusinessLogic, FirstTimeDataStore {
    var presenter: FirstTimePresentationLogic?
    var worker: FirstTimeWorker?

    // MARK: Login with facebook

    func loginWithFacebook(request: FirstTime.FacebookLogin.Request) {
        worker?.loginWithFacebook() { result in
            switch result {
            case .success:
                let response = FirstTime.FacebookLogin.Response(error: nil)
                self.presenter?.presentFacebookLogin(response: response)
            case .failure(let error):
                print("\(error)")
                let response = FirstTime.FacebookLogin.Response(error: error)
                self.presenter?.presentFacebookLogin(response: response)
            }
        }
    }
}
