//
//  EditWineInteractorTests.swift
//  mowine
//
//  Created by Josh Freed on 6/4/17.
//  Copyright (c) 2017 BleepSmazz. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

@testable import mowine
import XCTest

class EditWineInteractorTests: XCTestCase {
    // MARK: - Subject under test

    var sut: EditWineInteractor!
    let worker = MockEditWineWorker()

    // MARK: - Test lifecycle

    override func setUp() {
        super.setUp()
        setupEditWineInteractor()
    }

    override func tearDown() {
        super.tearDown()
    }

    // MARK: - Test setup

    func setupEditWineInteractor() {
        sut = EditWineInteractor(worker: worker)
    }

    // MARK: - Test doubles

    // MARK: - Tests

    func testSomething() {
        // Given

        // When

        // Then
    }
    
    
}
