//
//  EditWineWorker.swift
//  mowine
//
//  Created by Josh Freed on 2/18/17.
//  Copyright (c) 2017 BleepSmazz. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

class EditWineWorker {
    let varietyTranslator: VarietyTranslator
    
    init(varietyTranslator: VarietyTranslator) {
        self.varietyTranslator = varietyTranslator
    }
    
    // MARK: - Business Logic

    func saveWine(wine: Wine, request: EditWine.SaveWine.Request) throws {
        wine.name = request.name
        wine.rating = request.rating
        wine.variety = varietyTranslator.toCoreData(input: request.variety)
        wine.location = request.location
        wine.notes = request.notes
        
        if let price = request.price {
            wine.price = NSDecimalNumber(value: price)
        }else {
            wine.price = nil
        }
        
        let imageWorker = WineImageWorker()
        if let image = request.image {
            wine.image = imageWorker.convertToPNGData(image: image)
            wine.thumbnail = imageWorker.createThumbnail(from: image)
        }
        try wine.managedObjectContext?.save()
    }
}
