//
//  EditWineRouter.swift
//  mowine
//
//  Created by Josh Freed on 2/18/17.
//  Copyright (c) 2017 BleepSmazz. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol EditWineRouterInput {
    func navigateToMyWines()
}

class EditWineRouter: EditWineRouterInput {
    weak var viewController: EditWineViewController!

    // MARK: - Navigation

    func navigateToMyWines() {
        if viewController.isModal() {
            viewController.dismiss(animated: true, completion: nil)
        } else {
            let _ = viewController.navigationController?.popViewController(animated: true)
        }
    }

    // MARK: - Communication

    func passDataToNextScene(segue: UIStoryboardSegue) {
        // NOTE: Teach the router which scenes it can communicate with

        if segue.identifier == "ShowSomewhereScene" {
            passDataToSomewhereScene(segue: segue)
        }
    }

    func passDataToSomewhereScene(segue: UIStoryboardSegue) {
        // NOTE: Teach the router how to pass data to the next scene

        // let someWhereViewController = segue.destinationViewController as! SomeWhereViewController
        // someWhereViewController.output.name = viewController.output.name
    }
}
